name: Vite CI React Build

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

jobs:
  build-react-zustand:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¢ Echo
        run: 'echo "My name is ashik"'
      
      - name: ğŸƒ Checkout into runner
        uses: actions/checkout@v4
      
      - name: âš™ï¸ Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: ğŸ”¬ Dependencies
        run: npm ci
      
      - name: ğŸ” Linting
        run: npm run lint

      - name: ğŸ Type Checking
        run: npx tsc --noEmit

      - name: ğŸ¤– Build react project
        run: npm run build

      - name: ğŸ“‹ List Build Output
        run: ls -la dist
      
      - name: â˜ï¸ Upload artifects
        uses: actions/upload-artifect@v4
        with:
          name: vite-build
          path: dist