name: Vite CI React Build

on:
  - branches: [main]
  - pull-request: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¢ Echo
        run: 'echo "My name is ashik"'
      
      - name: ğŸƒ Checkout into runner
        run: actions/checkout@v4
      
      - name: âš™ï¸ Setup nodejs
        run: actions/setup-node@v4
      
      - name: ğŸ¤– Build react project
        run: npm run dev