name: Vite CI React Build

on:
  - branches: [main]
  - pull-request: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¢ Echo
        run: 'echo "My name is ashik"'
      
      - name: ğŸƒ Checkout into runner
        uses: actions/checkout@v4
      
      - name: âš™ï¸ Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: ğŸ”¬ Dependencies
        run: npm ci

      - name: ğŸ¤– Build react project
        run: npm run build